'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('raff', {
  getAll: () => ipcRenderer.invoke('lib:getAll'),
  addBook: (book) => ipcRenderer.invoke('lib:add', book),
  updateBook: (id, patch) => ipcRenderer.invoke('lib:update', id, patch),
  removeBook: (id) => ipcRenderer.invoke('lib:remove', id),
  restoreBook: (book) => ipcRenderer.invoke('lib:restore', book),
  borrowCopy: (bookId, payload) => ipcRenderer.invoke('lib:borrow', bookId, payload),
  returnLoan: (bookId, loanId, returnedAt) => ipcRenderer.invoke('lib:return', bookId, loanId, returnedAt),
  returnLoanParts: (bookId, loanId, volumes, returnedAt) => ipcRenderer.invoke('lib:returnParts', bookId, loanId, volumes, returnedAt),
  setReferenceNumber: (id, ref) => ipcRenderer.invoke('lib:setRef', id, ref),
  getStats: () => ipcRenderer.invoke('lib:stats'),
  getMeta: () => ipcRenderer.invoke('lib:meta'),
  getSettings: () => ipcRenderer.invoke('lib:getSettings'),
  updateSettings: (patch) => ipcRenderer.invoke('lib:updateSettings', patch),
  getActiveLoans: (opts) => ipcRenderer.invoke('lib:getActiveLoans', opts),
  applyLoanDuration: (days) => ipcRenderer.invoke('lib:applyLoanDuration', days),
  saveTablePdf: (html, fileHint) => ipcRenderer.invoke('lib:saveTablePdf', html, fileHint),
  peekNextRef: () => ipcRenderer.invoke('lib:peekNextRef'),

  exportJson: () => ipcRenderer.invoke('lib:exportJson'),
  exportCsv: () => ipcRenderer.invoke('lib:exportCsv'),
  exportTxt: () => ipcRenderer.invoke('lib:exportTxt'),
  exportPdf: () => ipcRenderer.invoke('lib:exportPdf'),
  saveLabelsPdf: (html, titleLabel) => ipcRenderer.invoke('lib:saveLabelsPdf', html, titleLabel),
  importJson: () => ipcRenderer.invoke('lib:importJson'),
  resetAll: () => ipcRenderer.invoke('lib:resetAll'),
  backup: () => ipcRenderer.invoke('lib:backup'),
  integrityCheck: () => ipcRenderer.invoke('lib:integrity'),
  repairIntegrity: () => ipcRenderer.invoke('lib:repairIntegrity'),
  openDataFolder: () => ipcRenderer.invoke('lib:openDataFolder'),
  exportOverdueCsv: () => ipcRenderer.invoke('lib:exportOverdueCsv'),

  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),

  // Window controls for the custom, in-app title bar.
  minimize: () => ipcRenderer.invoke('win:minimize'),
  toggleMaximize: () => ipcRenderer.invoke('win:toggleMaximize'),
  close: () => ipcRenderer.invoke('win:close'),
  isMaximized: () => ipcRenderer.invoke('win:isMaximized'),
  onWindowStateChange: (callback) => {
    ipcRenderer.on('win:state', (_e, state) => callback(state));
  },
});

contextBridge.exposeInMainWorld('raff4', {
  snapshot: () => ipcRenderer.invoke('v4:snapshot'),
  getEntity: (entity) => ipcRenderer.invoke('v4:getEntity', entity),
  createEntity: (entity, payload) => ipcRenderer.invoke('v4:createEntity', entity, payload),
  updateEntity: (entity, id, patch) => ipcRenderer.invoke('v4:updateEntity', entity, id, patch),
  deleteEntity: (entity, id, reason) => ipcRenderer.invoke('v4:deleteEntity', entity, id, reason),
  restoreTrash: (id) => ipcRenderer.invoke('v4:restoreTrash', id),
  purgeTrash: (id) => ipcRenderer.invoke('v4:purgeTrash', id),
  createRecord: (payload) => ipcRenderer.invoke('v4:createRecord', payload),
  updateRecord: (id, patch) => ipcRenderer.invoke('v4:updateRecord', id, patch),
  addItems: (id, payload) => ipcRenderer.invoke('v4:addItems', id, payload),
  updateItem: (id, patch) => ipcRenderer.invoke('v4:updateItem', id, patch),
  checkout: (payload) => ipcRenderer.invoke('v4:checkout', payload),
  returnItems: (payload) => ipcRenderer.invoke('v4:returnItems', payload),
  renewLoan: (id, payload) => ipcRenderer.invoke('v4:renewLoan', id, payload),
  placeHold: (payload) => ipcRenderer.invoke('v4:placeHold', payload),
  updateHoldStatus: (id, status) => ipcRenderer.invoke('v4:updateHoldStatus', id, status),
  startInventory: (payload) => ipcRenderer.invoke('v4:startInventory', payload),
  scanInventory: (id, code) => ipcRenderer.invoke('v4:scanInventory', id, code),
  closeInventory: (id) => ipcRenderer.invoke('v4:closeInventory', id),
  createTransfer: (payload) => ipcRenderer.invoke('v4:createTransfer', payload),
  receiveTransfer: (id, payload) => ipcRenderer.invoke('v4:receiveTransfer', id, payload),
  cancelTransfer: (id, reason) => ipcRenderer.invoke('v4:cancelTransfer', id, reason),
  refreshNotifications: () => ipcRenderer.invoke('v4:refreshNotifications'),
  markNotification: (id, read) => ipcRenderer.invoke('v4:markNotification', id, read),
  markAllNotifications: (read) => ipcRenderer.invoke('v4:markAllNotifications', read),
  bulkUpdateRecords: (ids, patch) => ipcRenderer.invoke('v4:bulkUpdateRecords', ids, patch),
  mergeAuthorities: (keeper, duplicates) => ipcRenderer.invoke('v4:mergeAuthorities', keeper, duplicates),
  validateIsbn: (value) => ipcRenderer.invoke('v4:validateIsbn', value),
  search: (query, filters) => ipcRenderer.invoke('v4:search', query, filters),
  setSettings: (patch) => ipcRenderer.invoke('v4:setSettings', patch),
  authenticateUser: (id, pin) => ipcRenderer.invoke('v4:authenticateUser', id, pin),
  auditLog: (filters) => ipcRenderer.invoke('v4:auditLog', filters),
  createSnapshot: (reason) => ipcRenderer.invoke('v4:createSnapshot', reason),
  listBackups: () => ipcRenderer.invoke('v4:listBackups'),
  restoreBackup: (name) => ipcRenderer.invoke('v4:restoreBackup', name),
  integrity: () => ipcRenderer.invoke('v4:integrity'),
  repairSafe: () => ipcRenderer.invoke('v4:repairSafe'),
  startLocalOpac: (options) => ipcRenderer.invoke('v4:opacStart', options),
  stopLocalOpac: () => ipcRenderer.invoke('v4:opacStop'),
  localOpacStatus: () => ipcRenderer.invoke('v4:opacStatus'),
  exportMarc: () => ipcRenderer.invoke('v4:exportMarc'),
  importMarc: () => ipcRenderer.invoke('v4:importMarc'),
  exportMarcIso: () => ipcRenderer.invoke('v4:exportMarcIso'),
  importMarcIso: () => ipcRenderer.invoke('v4:importMarcIso'),
  exportDublinCore: () => ipcRenderer.invoke('v4:exportDublinCore'),
  exportJsonLd: () => ipcRenderer.invoke('v4:exportJsonLd'),
  importBibTex: () => ipcRenderer.invoke('v4:importBibTex'),
  importRis: () => ipcRenderer.invoke('v4:importRis'),
  exportBibTex: () => ipcRenderer.invoke('v4:exportBibTex'),
  exportRis: () => ipcRenderer.invoke('v4:exportRis'),
  exportTransfer: () => ipcRenderer.invoke('v4:exportTransfer'),
  importTransfer: () => ipcRenderer.invoke('v4:importTransfer'),
});
